name: tf-destroy-dev

env:
    environment: dev
    terraform_version: 1.6.6
on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type 'DESTROY' to confirm"
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  tf-destroy-dev:
    if: ${{ github.event.inputs.confirm_destroy == 'DESTROY' }}
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_Destroy_Dev
          aws-region: us-east-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.terraform_version }}

      - name: Terraform Init
        run: terraform init

      - name: Show Terraform Destroy Plan
        run: terraform plan -destroy -var-file="env/${{ env.environment }}/variables.tfvars"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -var-file="env/${{ env.environment }}/variables.tfvars"